# Generated by Django 5.0 on 2023-12-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('on_review', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='on_review', max_length=20),
        ),
    ]
