# Generated by Django 5.0 on 2023-12-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_hotel_id_review_hotel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='review',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
